
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "103.155.216.231"
    port: 12100
    username: "Phogapro"
    password: "Phogapr0123"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "171.248.46.143"
    port: 13751
    username: "thanh4"
    password: "thanh@2026#"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1

rules:
  - MATCH,AUTO
