
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "103.155.216.231"
    port: 12100
    username: "Phogapro"
    password: "Phogapr0123"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "14.241.72.253"
    port: 17862
    username: "IxibFI"
    password: "KiYaaM"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "103.82.27.114"
    port: 12500
    username: "Phogapro"
    password: "Phogapr0123"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
