
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "103.155.216.231"
    port: 12100
    username: "Phogapro"
    password: "Phogapr0123"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "14.161.29.217"
    port: 15122
    username: "v2-122-799594"
    password: "FEAHO"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1

rules:
  - MATCH,AUTO
