
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "proxy07189.lproxy.online"
    port: 27579
    username: "mmobox33"
    password: "njgzntyyotk1"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "dancu01.trumproxy.vn"
    port: 14028
    username: "userGxd"
    password: "D5R6uMtL"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "118.71.214.14"
    port: 33274
    username: "u17d48e03"
    password: "d705673a69ff9eea"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
