
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "42.116.219.249"
    port: 31175
    username: "ud4a45b1b"
    password: "4f85224914801be8"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "103.179.189.197"
    port: 15402
    username: "2pbackup2"
    password: "2pbackup2"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "42.115.149.127"
    port: 30093
    username: "u59cb5431"
    password: "ceb56ce00cd3cf75"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
