
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "42.113.91.239"
    port: 36400
    username: "uf886093d"
    password: "dde5e61a9f0beaf4"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "103.166.184.92"
    port: 13704
    username: "new"
    password: "new"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "171.252.33.175"
    port: 8045
    username: "modvip5"
    password: "mje2nju4njk2"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
