
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "103.179.188.222"
    port: 23297
    username: "backup3"
    password: "backup3"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "dancu01.trumproxy.vn"
    port: 14006
    username: "useruYf"
    password: "fd0eNV6R"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "sv1.proxysocks5.vn"
    port: 44214
    username: "UFpzr5JA"
    password: "cSpPRpwzaE"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
