
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "210.245.34.106"
    port: 53322
    username: "nz73"
    password: "lhpy"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "103.82.27.114"
    port: 12147
    username: "Phogapro"
    password: "8vED5g6ItlWu43"
    udp: true

  - name: BACKUP2
    type: "socks5"
    server: "160.250.166.88"
    port: 20091
    username: "jpRZLq"
    password: "vUPONK"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
