
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "14.225.217.69"
    port: 57440
    username: "lAYGm52M"
    password: "SzuPA4eDfc"
    udp: true

  - name: BACKUP1
    type: "socks5"
    server: "160.250.166.88"
    port: 20091
    username: "jpRZLq"
    password: "vUPONK"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "113.22.41.167"
    port: 37151
    username: "ucec424b7"
    password: "257afed9844d5110"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
