
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "42.117.91.212"
    port: 13810
    username: "boxphone21x24"
    password: "ntm2njcxndcxna=="
    udp: true

  - name: BACKUP1
    type: "http"
    server: "42.118.130.47"
    port: 39553
    username: "u4940ac36"
    password: "6275b532598fe5c0"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "103.179.189.197"
    port: 36590
    username: "backup5"
    password: "backup5"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
