
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "103.82.192.234"
    port: 19803
    username: "Macdinh1qu6"
    password: "1779867303"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "118.71.214.208"
    port: 33319
    username: "ua69093f4"
    password: "b2329df1a61695ba"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "sv1.proxysocks5.vn"
    port: 45777
    username: "asS7GDoi"
    password: "0hcPXWHICO"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
