
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "103.166.184.65"
    port: 22649
    username: "21yinew"
    password: "21yinew"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "118.71.67.81"
    port: 33823
    username: "ua6ae74f5"
    password: "8ec072db97f29a66"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "103.82.194.60"
    port: 14412
    username: "2pbackup1"
    password: "2pbackup1"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
