
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "14.225.217.69"
    port: 57495
    username: "fz5oe4jj"
    password: "rNktLInKPS"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "113.167.46.121"
    port: 14027
    username: "userZyQ"
    password: "waBJgzEk"
    udp: true

  - name: BACKUP2
    type: "socks5"
    server: "160.250.166.88"
    port: 20433
    username: "phoga1"
    password: "Phoga654321"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
