
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "1.53.63.97"
    port: 59399
    username: "modvip3"
    password: "mdc2mjk3ndk4mtq0"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "222.255.180.113"
    port: 38872
    username: "phogapro"
    password: "phogapro"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "103.82.27.114"
    port: 12500
    username: "Phogapro"
    password: "Phogapr0123"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
