
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "sv1.proxysocks5.vn"
    port: 57378
    username: "UwphrI5s"
    password: "0z51QswVk6"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "103.82.194.108"
    port: 37778
    username: "2pbackup1"
    password: "2pbackup1"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "222.255.180.44"
    port: 25895
    username: "new"
    password: "new"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
