
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "210.245.34.106"
    port: 47146
    username: "zcqz"
    password: "0hjx"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "14.161.29.217"
    port: 15132
    username: "v2-132-789327"
    password: "FQKGR"
    udp: true

  - name: BACKUP2
    type: "socks5"
    server: "160.250.166.88"
    port: 21322
    username: "OPcesO"
    password: "TUuqYb"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
