
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "14.225.217.69"
    port: 57501
    username: "ZXL6gR0L"
    password: "tq8pya8GWh"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "103.82.192.234"
    port: 19803
    username: "phogapro"
    password: "phogapro"
    udp: true

  - name: BACKUP2
    type: "socks5"
    server: "203.175.97.116"
    port: 20584
    username: "phoga"
    password: "phoga123456"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
