
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "103.82.192.234"
    port: 19803
    username: "Macdinh1qu6"
    password: "1779867303"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "171.252.33.175"
    port: 8045
    username: "modvip5"
    password: "mje2nju4njk2"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "160.250.166.88"
    port: 20064
    username: "backup3"
    password: "VEuJrW"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
