
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "113.22.68.43"
    port: 38033
    username: "uf841dff7"
    password: "020cdb8146509785"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "103.166.184.186"
    port: 27109
    username: "phogapro"
    password: "phogapro"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "42.113.31.71"
    port: 64126
    username: "mmobackup02"
    password: "mdi5odewmzm1"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
