
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "210.245.34.106"
    port: 50562
    username: "aucr"
    password: "b8xl"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "171.248.253.125"
    port: 20129
    username: "thanh2"
    password: "thanh@2026#"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1

rules:
  - MATCH,AUTO
