
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "118.69.71.241"
    port: 51179
    username: "q7kq"
    password: "l5v2"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "14.161.29.217"
    port: 15144
    username: "v2-144-542901"
    password: "GWRMN"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1

rules:
  - MATCH,AUTO
