
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "103.166.184.65"
    port: 22649
    username: "21yinew"
    password: "21yinew"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "103.82.27.114"
    port: 12147
    username: "Phogapro"
    password: "8vED5g6ItlWu43"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "171.246.99.152"
    port: 8045
    username: "modvip5"
    password: "mje2nju4njk2"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
