
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "210.245.34.106"
    port: 51179
    username: "i4ty"
    password: "2g0g"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "118.70.171.101"
    port: 46631
    username: "dgfpWf"
    password: "THOsOf"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "222.255.180.113"
    port: 38872
    username: "phogapro"
    password: "phogapro"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
