
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "222.255.180.113"
    port: 38872
    username: "Macdinhl4h3"
    password: "1779856168"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "14.250.78.12"
    port: 14270
    username: "modvipbk1"
    password: "otm1nzqzotm2"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "14.250.74.211"
    port: 27717
    username: "94pg1"
    password: "ffJc122wRe"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
