
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "103.166.184.65"
    port: 22649
    username: "21yinew"
    password: "21yinew"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "42.115.149.85"
    port: 35091
    username: "u9dacac1b"
    password: "347f5f146d4f8f75"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "dancu01.trumproxy.vn"
    port: 14027
    username: "userZyQ"
    password: "waBJgzEk"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
