
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "103.166.184.65"
    port: 22649
    username: "21yinew"
    password: "21yinew"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "1.53.23.41"
    port: 33581
    username: "u6d5e91d0"
    password: "3d8e0d51841e4402"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "27.65.255.98"
    port: 56434
    username: "unityhelpdesk"
    password: "@helpdesk@123"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
