
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "113.177.130.172"
    port: 43744
    username: "zlgk"
    password: "0cmn"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "171.248.39.160"
    port: 51471
    username: "thanh"
    password: ":thanh@2026#"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1

rules:
  - MATCH,AUTO
