
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "171.246.241.34"
    port: 36860
    username: "modvip1.1"
    password: "ewtreytrey12341"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "113.22.41.2"
    port: 37344
    username: "udd9c2476"
    password: "c9b6f8b1841eb592"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "14.250.74.211"
    port: 57958
    username: "94pg2"
    password: "AyTadKHGk5"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
