
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "171.246.241.34"
    port: 36860
    username: "modvip1.1"
    password: "ewtreytrey12341"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "113.22.41.167"
    port: 37151
    username: "ucec424b7"
    password: "257afed9844d5110"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "116.109.98.85"
    port: 42478
    username: "unityhelpdesk"
    password: "@helpdesk@123"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
