
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "103.82.27.208"
    port: 35214
    username: "phogapronewnew"
    password: "phogapronewnew"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "14.225.217.69"
    port: 57593
    username: "4Tafn8m9"
    password: "bZniM3WV01"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "171.246.104.198"
    port: 58281
    username: "mmobackup01"
    password: "mty0mjiyndux"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
