
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "171.241.76.96"
    port: 25649
    username: "modvip2"
    password: "mdk4nzu4ndq3"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "113.177.130.85"
    port: 51179
    username: "bi7z"
    password: "t3nk"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "222.255.180.113"
    port: 38872
    username: "phogapro"
    password: "phogapro"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
