
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "103.82.25.80"
    port: 32703
    username: "pgfpt2605"
    password: "pgfpt2605"
    udp: true

  - name: BACKUP1
    type: "socks5"
    server: "160.250.166.88"
    port: 20433
    username: "phoga1"
    password: "Phoga654321"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "113.22.41.127"
    port: 35129
    username: "u56f3def9"
    password: "a30c0d84c29b8e22"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
