
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "1.52.180.51"
    port: 59399
    username: "modvip3"
    password: "mdc2mjk3ndk4mtq0"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "103.179.188.222"
    port: 23297
    username: "backup3"
    password: "backup3"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "14.250.75.61"
    port: 63376
    username: "94pg3"
    password: "ZHpkramgU9"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
