
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "103.166.184.80"
    port: 36142
    username: "phogapro"
    password: "phogapro"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "210.245.34.106"
    port: 42575
    username: "a7j1"
    password: "d1l4"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "103.82.27.114"
    port: 12500
    username: "Phogapro"
    password: "Phogapr0123"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
