
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "116.102.206.208"
    port: 57350
    username: "Phogapro01"
    password: "VY46jDhjCj"
    udp: true

  - name: BACKUP1
    type: "socks5"
    server: "203.175.97.116"
    port: 20584
    username: "phoga"
    password: "phoga123456"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "103.82.27.114"
    port: 12147
    username: "Phogapro"
    password: "8vED5g6ItlWu43"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
