
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "103.82.25.80"
    port: 32703
    username: "pgfpt2605"
    password: "pgfpt2605"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "118.71.206.6"
    port: 23141
    username: "modvipbk2"
    password: "mdq2mzi3mzkzmg=="
    udp: true

  - name: BACKUP2
    type: "http"
    server: "dancu01.trumproxy.vn"
    port: 14028
    username: "userGxd"
    password: "D5R6uMtL"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
