
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:

  - name: MAIN
    type: "http"
    server: "1.53.23.240"
    port: 37413
    username: "uf3830c7d"
    password: "2461a83add604d29"
    udp: true

  - name: BACKUP1
    type: "http"
    server: "103.166.184.186"
    port: 29254
    username: "2pbackuppro1"
    password: "2pbackuppro1"
    udp: true

  - name: BACKUP2
    type: "http"
    server: "103.179.189.197"
    port: 15402
    username: "2pbackup2"
    password: "2pbackup2"
    udp: true


proxy-groups:
  - name: AUTO
    type: fallback
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    proxies:
      - MAIN
      - BACKUP1
      - BACKUP2

rules:
  - MATCH,AUTO
